from app.models.hardware import (
    BiosInfo,
    DriverInfo,
    FullScan,
    HardwareInfo,
    MemoryModule,
    SystemInfo,
    UpdatesInfo,
)


def make_scan(
    *,
    ram_gb: float = 32.0,
    secure_boot: str = "Habilitado",
    virtualization: str = "Desabilitado",
    power_plan: str = "Equilibrado",
    motherboard_model: str = "B650 AORUS ELITE AX",
    bios_version: str = "F20",
    ram_xmp_active: bool | None = True,
    rebar_enabled: bool | None = True,
    ram_speed_mhz: int = 6000,
    pending_reboot: bool | None = False,
    last_hotfix_age_days: int | None = 10,
    available_windows_updates: int | None = 0,
    outdated_drivers: list[DriverInfo] | None = None,
    hvci_running: str = "Desabilitado",
    vbs_running: str = "Desabilitado",
    fast_startup: str = "Desabilitado",
    storage_mode: str = "AHCI",
    cpu_vendor: str = "AuthenticAMD",
) -> FullScan:
    sys_info = SystemInfo(
        os_name="Windows",
        os_version="10.0.26200",
        os_build="11",
        architecture="AMD64",
        hostname="DESKTOP-TEST",
        power_plan=power_plan,
    )
    hw = HardwareInfo(
        cpu_name="AMD Ryzen 7 7700X",
        cpu_cores=8,
        cpu_threads=16,
        cpu_freq_mhz=4500.0,
        ram_total_gb=ram_gb,
        ram_used_gb=8.0,
        gpu_name="NVIDIA GeForce RTX 4070",
        gpu_driver_version="552.22",
        motherboard_vendor="GIGABYTE",
        motherboard_model=motherboard_model,
        storage=[{"device": "C:", "mountpoint": "C:\\", "fstype": "NTFS",
                   "total_gb": 500.0, "used_gb": 200.0}],
        ram_modules=[
            MemoryModule(
                manufacturer="G.Skill",
                part_number="F5-6000J3038F16G",
                capacity_gb=ram_gb / 2,
                configured_clock_mhz=ram_speed_mhz,
                rated_speed_mhz=ram_speed_mhz,
                form_factor="DIMM",
            ),
        ],
        ram_xmp_active=ram_xmp_active,
        gpu_vram_gb=12.0,
        rebar_enabled=rebar_enabled,
        sensors={"Temperature": [{"name": "CPU", "parent": "/cpu/0", "value": 55.0}]},
    )
    bios = BiosInfo(
        vendor="American Megatrends",
        version=bios_version,
        release_date="20240101",
        secure_boot=secure_boot,
        tpm="Presente",
        tpm_version="2.0",
        virtualization=virtualization,
        boot_mode="UEFI",
        hyper_v_enabled="Desabilitado",
        vbs_running=vbs_running,
        hvci_running=hvci_running,
        storage_mode=storage_mode,
        fast_startup=fast_startup,
        hibernation="Habilitado",
        cpu_vendor=cpu_vendor,
    )
    updates = UpdatesInfo(
        pending_reboot=pending_reboot,
        last_hotfix_id="KB5030000",
        last_hotfix_date="2026-04-26",
        last_hotfix_age_days=last_hotfix_age_days,
        available_windows_updates=available_windows_updates,
        update_check_status="Concluído.",
        outdated_drivers=outdated_drivers or [],
        drivers_total=12,
    )
    return FullScan(
        system=sys_info,
        hardware=hw,
        bios=bios,
        updates=updates,
        collected_at="2026-05-06T12:00:00",
    )
